version: '3'
services:
  app:
    container_name: ${PROJECT_NAME}_app
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - '${PORT}:${PORT}'
    links:
      - mongo
    expose:
      - ${PORT}

  mongo:
    container_name: ${PROJECT_NAME}_mongo
    image: mongo
    # volumes:
      # - ./mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_MONGO_PASS}
    ports:
      - '27017:27017'


